spring:
  datasource:
    url: jdbc:mysql://localhost/demo
    username: demo
    password: demo
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      encoding: utf-8
  messages:
    basename: messages, ValidationMessages
# logging:
#   level:
#     root: debug
